Add ability to check for absolute files used as dlls
Added script and makefile target for detecting absolute filenames as
seen in bug 1365658.  The make target is not yet used in Jenkins
builds.  Because the check takes more than 30 seconds, it was not
added as part of the normal "make package" work, a 20+% increase in
running make is not worthwhile for a rare bug which may never happen
again.

Example:

$ time make find-absolute-dlls
sqf/build-scripts/find-abs-dlls
Searching <my-directory>
for absolute files used as dlls ...

ERROR: Found 6 files with absolute filenames as dlls:

sql/lib/linux/64bit/debug/sqlci
  NEEDED               /home/tools/jdk1.7.0_09_64/jre/lib/amd64/server/libjsig.so

sql/lib/linux/64bit/debug/tdm_arkesp
  NEEDED               /home/tools/jdk1.7.0_09_64/jre/lib/amd64/server/libjsig.so

sql/lib/linux/64bit/debug/tdm_udrserv
  NEEDED               /home/tools/jdk1.7.0_09_64/jre/lib/amd64/server/libjsig.so

sql/lib/linux/64bit/debug/tdm_arkcmp
  NEEDED               /home/tools/jdk1.7.0_09_64/jre/lib/amd64/server/libjsig.so

sql/lib/linux/64bit/debug/mxssmp
  NEEDED               /home/tools/jdk1.7.0_09_64/jre/lib/amd64/server/libjsig.so

sql/lib/linux/64bit/debug/mxsscp
  NEEDED               /home/tools/jdk1.7.0_09_64/jre/lib/amd64/server/libjsig.so

make: *** [find-absolute-dlls] Error 6

real    0m39.801s
user    0m26.196s
sys     0m9.438s

Also made a small cleanup to the existing check_man script.

Change-Id: I22babe08dbf8a4620603fc670acc6b05e831222f